### ISSUE TITLE
Remove or disable output to console

### ISSUE THREAD

**Issue by morassman** [thomasbratt/NSchedule#3]
Each time the scheduler completes it prints out 'No more tasks.' to the console. This output interferes with the output produced by the host application. It would be very helpful if a way can be provided to disable it.

**Comment by thomasbratt** [comment]
@morassman you're right - it shouldn't be there. I'll remove it or merge in the request from @NGPixel

**Comment by thomasbratt** [comment]
Fixed in 0.4.0 - thanks for the contributions and patience :)
